name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        env:
            CI: true

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: corepack enable
            - run: yarn install
            - run: yarn dist
            - run: yarn test

            # Coverage.
            - name: Run coverage
              run: |
                  yarn coverage
                  yarn coverage:report
            - name: Report coverage
              uses: codecov/codecov-action@v5
              with:
                  files: coverage/coverage.lcov
